[phases.setup]
nixPkgs = ["python312", "nodejs_22", "nodePackages.pnpm", "pkg-config", "mysqlclient"]

[phases.install]
cmds = [
  "pip install -r requirements/base.txt whitenoise gunicorn",
  "cd frontend && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd frontend && pnpm build",
  "cd backend && python manage.py collectstatic --noinput"
]
