# Generated by Django 6.0.6 on 2026-06-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'type',
                    models.CharField(
                        choices=[('earning', 'Earning'), ('spending', 'Spending')], max_length=10
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Inactive categories are hidden from pickers but preserved for historical budget lines. Use instead of hard-deleting.',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'household',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='categories',
                        to='users.household',
                    ),
                ),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['type', 'name'],
                'unique_together': {('household', 'name', 'type')},
            },
        ),
    ]
