"""
tests/api/v1/auth/test_register.py — Tests for POST /auth/register.

auth/conftest.py provides: client, valid_payload, registered_user.
"""

import pytest

from users.models import CustomUser


@pytest.mark.django_db
class TestAuthRegister:
    @pytest.fixture(autouse=True)
    def mock_login(self, mocker):
        """Patch Django's login() to avoid session handling in tests."""
        return mocker.patch('api.v1.auth.login')

    def test_successful_registration_returns_user(self, client, valid_payload):
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 200
        data = response.json()
        assert data['email'] == valid_payload['email']
        assert data['first_name'] == 'John'
        assert data['last_name'] == 'Doe'
        assert data['households'] == []

    def test_username_autogenerated_from_email_local_part(self, client, valid_payload):
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 200
        assert response.json()['username'] == 'john'

    def test_username_gets_suffix_when_local_part_taken(
        self, client, valid_payload, registered_user
    ):
        new_payload = valid_payload.copy()
        new_payload['email'] = 'john@otherdomain.com'
        response = client.post('/auth/register', json=new_payload)
        assert response.status_code == 200
        username = response.json()['username']
        assert username.startswith('john_')
        assert len(username) > len('john_')

    def test_duplicate_email_returns_400(self, client, valid_payload, registered_user):
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400
        assert 'email already exists' in response.json()['detail'].lower()

    def test_invalid_email_format_returns_400(self, client, valid_payload):
        valid_payload['email'] = 'notanemail'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_mismatched_passwords_returns_400(self, client, valid_payload):
        valid_payload['confirm_password'] = 'DifferentPassword1!'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_weak_password_no_uppercase_returns_400(self, client, valid_payload):
        valid_payload['password'] = 'nolowercase1234!'
        valid_payload['confirm_password'] = 'nolowercase1234!'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_weak_password_no_lowercase_returns_400(self, client, valid_payload):
        valid_payload['password'] = 'NOLOWERCASE1234!'
        valid_payload['confirm_password'] = 'NOLOWERCASE1234!'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_weak_password_no_digit_returns_400(self, client, valid_payload):
        valid_payload['password'] = 'NoDigitsHere!!!'
        valid_payload['confirm_password'] = 'NoDigitsHere!!!'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_weak_password_no_special_char_returns_400(self, client, valid_payload):
        valid_payload['password'] = 'NoSpecialChar1234'
        valid_payload['confirm_password'] = 'NoSpecialChar1234'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400

    def test_optional_name_fields_default_to_empty(self, client, valid_payload):
        del valid_payload['first_name']
        del valid_payload['last_name']
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 200
        data = response.json()
        assert data['first_name'] == ''
        assert data['last_name'] == ''

    def test_user_is_created_in_database(self, client, valid_payload):
        client.post('/auth/register', json=valid_payload)
        assert CustomUser.objects.filter(email=valid_payload['email']).exists()

    def test_email_is_normalised_to_lowercase(self, client, valid_payload):
        valid_payload['email'] = 'John@Example.COM'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 200
        assert response.json()['email'] == 'john@example.com'

    def test_duplicate_email_case_insensitive_returns_400(
        self, client, valid_payload, registered_user
    ):
        valid_payload['email'] = 'JOHN@EXAMPLE.COM'
        response = client.post('/auth/register', json=valid_payload)
        assert response.status_code == 400
