"""
api/v1/auth.py — v1 authentication endpoints.

Endpoints:
    POST  /api/v1/auth/register    — create a new user account
    POST  /api/v1/auth/login       — authenticate with email + password, start a session
    POST  /api/v1/auth/logout      — invalidate the current session
    GET   /api/v1/auth/me          — return the current authenticated user
    PATCH /api/v1/auth/me          — update the current user's profile fields
    POST  /api/v1/auth/me/password — change the current user's password
"""

import logging
import secrets

from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from ninja import Router
from ninja.errors import HttpError
from ninja.security import django_auth

from schemas.auth import (
    LoginRequest,
    MessageResponse,
    RegisterRequest,
    UpdatePasswordRequest,
    UpdateProfileRequest,
    UserSchema,
)
from users.models import CustomUser
from users.validators import validate_email_format

logger = logging.getLogger(__name__)

router = Router(tags=['Auth'])

_username_validator = UnicodeUsernameValidator()


# ── Endpoints ─────────────────────────────────────────────────────────────────


@router.post('/auth/register', response=UserSchema)
def auth_register(request, payload: RegisterRequest):
    """Creates a new user account and starts a session.

    The username is autogenerated from the email local part. If the local
    part is already taken, a short random suffix is appended (e.g. john_a1b2).
    The email is normalised to lowercase before storage and uniqueness checks.

    Args:
        request: The HTTP request object.
        payload: Registration fields including email, password, and
            confirm_password.

    Returns:
        A UserSchema representing the newly created and logged-in user.

    Raises:
        HttpError: 400 if validation fails or the email is already registered.
    """
    if email_error := validate_email_format(payload.email):
        raise HttpError(400, email_error)

    email = payload.email.lower()

    if payload.password != payload.confirm_password:
        raise HttpError(400, 'Passwords do not match.')

    unsaved_user = CustomUser(
        email=email,
        first_name=payload.first_name,
        last_name=payload.last_name,
    )
    try:
        validate_password(payload.password, user=unsaved_user)
    except ValidationError as e:
        raise HttpError(400, ' '.join(e.messages)) from None

    if CustomUser.objects.filter(email=email).exists():
        raise HttpError(400, 'An account with this email already exists.')

    username = _generate_username_from_email(email)

    try:
        user = CustomUser.objects.create_user(
            username=username,
            email=email,
            password=payload.password,
            first_name=payload.first_name,
            last_name=payload.last_name,
        )
    except IntegrityError:
        raise HttpError(400, 'An account with this email already exists.') from None

    login(request, user)
    logger.info(f'New user registered: {user.username} ({user.email}).')
    return _serialize_user(user)


@router.post('/auth/login', response=UserSchema)
def auth_login(request, payload: LoginRequest):
    """Authenticates a user by email and password and starts a session.

    The email is normalised to lowercase before lookup. Django's
    authenticate() expects a username, so the username is resolved
    from the provided email before authentication is attempted.

    Args:
        request: The HTTP request object.
        payload: Login credentials containing email and password.

    Returns:
        A UserSchema representing the authenticated user.

    Raises:
        HttpError: 401 if the email is not found or the password is incorrect.
    """
    email = payload.email.lower()

    try:
        user = CustomUser.objects.get(email=email)
    except CustomUser.DoesNotExist:
        raise HttpError(401, 'Invalid email or password.') from None
    except CustomUser.MultipleObjectsReturned:
        logger.error(f'Multiple users found for email: {email}')
        raise HttpError(401, 'Invalid email or password.') from None

    authenticated_user = authenticate(
        request,
        username=user.username,
        password=payload.password,
    )

    if authenticated_user is None:
        raise HttpError(401, 'Invalid email or password.')

    login(request, authenticated_user)
    logger.info(f'User {authenticated_user.username} logged in.')
    return _serialize_user(
        CustomUser.objects.prefetch_related('households').get(pk=authenticated_user.pk)
    )


@router.post('/auth/logout', auth=django_auth, response=MessageResponse)
def auth_logout(request):
    """Invalidates the current session.

    Args:
        request: The HTTP request object. Must be authenticated.

    Returns:
        A MessageResponse confirming the user has been logged out.
    """
    logger.info(f'User {request.user.username} logged out.')
    logout(request)
    return MessageResponse(message='Logged out successfully.')


@router.get('/auth/me', auth=django_auth, response=UserSchema)
def auth_me(request):
    """Returns the currently authenticated user.

    Called on page load to check whether a valid session already exists.

    Args:
        request: The HTTP request object. Must be authenticated.

    Returns:
        A UserSchema representing the current user.
    """
    user = CustomUser.objects.prefetch_related('households').get(pk=request.user.pk)
    return _serialize_user(user)


@router.patch('/auth/me', auth=django_auth, response=UserSchema)
def auth_update_profile(request, payload: UpdateProfileRequest):
    """Updates the current user's profile fields.

    All fields are optional — only fields explicitly included in the request
    body are updated. An empty payload is a valid no-op and returns the
    current user unchanged.

    Validation rules:
    - first_name / last_name: blank strings are rejected.
    - email: normalised to lowercase, format-validated, must be unique
      excluding the current user.
    - username: must satisfy Django's UnicodeUsernameValidator, max 150
      chars, and be unique excluding the current user.

    Args:
        request: The HTTP request object. Must be authenticated.
        payload: Partial profile update fields.

    Returns:
        A UserSchema representing the updated user.

    Raises:
        HttpError: 400 for blank values, invalid formats, or uniqueness
            violations.
    """
    user: CustomUser = request.user
    update_fields: list[str] = []

    if payload.first_name is not None:
        if not payload.first_name.strip():
            raise HttpError(400, 'First name cannot be blank.')
        user.first_name = payload.first_name
        update_fields.append('first_name')

    if payload.last_name is not None:
        if not payload.last_name.strip():
            raise HttpError(400, 'Last name cannot be blank.')
        user.last_name = payload.last_name
        update_fields.append('last_name')

    if payload.email is not None:
        if not payload.email.strip():
            raise HttpError(400, 'Email cannot be blank.')
        if email_error := validate_email_format(payload.email):
            raise HttpError(400, email_error)
        email = payload.email.lower()
        if CustomUser.objects.filter(email=email).exclude(pk=user.pk).exists():
            raise HttpError(400, 'An account with this email already exists.')
        user.email = email
        update_fields.append('email')

    if payload.username is not None:
        if not payload.username.strip():
            raise HttpError(400, 'Username cannot be blank.')
        if len(payload.username) > 150:
            raise HttpError(400, 'Username must be 150 characters or fewer.')
        try:
            _username_validator(payload.username)
        except ValidationError as e:
            raise HttpError(400, ' '.join(e.messages)) from None
        if CustomUser.objects.filter(username=payload.username).exclude(pk=user.pk).exists():
            raise HttpError(400, 'This username is already taken.')
        user.username = payload.username
        update_fields.append('username')

    if update_fields:
        try:
            user.save(update_fields=update_fields)
        except IntegrityError:
            if (
                'email' in update_fields
                and CustomUser.objects.filter(email=user.email).exclude(pk=user.pk).exists()
            ):
                raise HttpError(400, 'An account with this email already exists.') from None
            if (
                'username' in update_fields
                and CustomUser.objects.filter(username=user.username).exclude(pk=user.pk).exists()
            ):
                raise HttpError(400, 'This username is already taken.') from None
            raise HttpError(400, 'Unable to update profile due to a conflicting value.') from None
        logger.info(f'User {user.pk} updated profile fields: {update_fields}.')

    user.refresh_from_db()
    user = CustomUser.objects.prefetch_related('households').get(pk=user.pk)
    return _serialize_user(user)


@router.post('/auth/me/password', auth=django_auth, response={204: None})
def auth_update_password(request, payload: UpdatePasswordRequest):
    """Changes the current user's password.

    Verifies the current password before applying the change, then
    re-authenticates the session so the user is not logged out.

    Args:
        request: The HTTP request object. Must be authenticated.
        payload: Current password, new password, and confirmation.

    Returns:
        None — 204 No Content on success.

    Raises:
        HttpError: 400 if current_password is wrong, passwords don't match,
            or new_password fails Django's validators.
    """
    user: CustomUser = request.user

    if not user.check_password(payload.current_password):
        raise HttpError(400, 'Current password is incorrect.')

    if payload.new_password != payload.confirm_new_password:
        raise HttpError(400, 'New passwords do not match.')

    try:
        validate_password(payload.new_password, user=user)
    except ValidationError as e:
        raise HttpError(400, ' '.join(e.messages)) from None

    user.set_password(payload.new_password)
    user.save()

    # Keep the session alive — Django rotates the session hash on password
    # change, which would otherwise log out the user immediately.
    update_session_auth_hash(request, user)
    logger.info(f'User {user.pk} changed their password.')

    return 204, None


# ── Helpers ───────────────────────────────────────────────────────────────────


def _generate_username_from_email(email: str) -> str:
    """Derives a unique username from the local part of an email address.

    Assumes the email has already been validated and normalised to lowercase.
    The local part is truncated to 141 characters before any suffix is added
    to ensure the final username never exceeds Django's 150-character limit.

    If the local part is already taken, a 4-character random hex suffix is
    appended and retried up to 10 times before falling back to an 8-character
    suffix.

    Examples:
        john@gmail.com  → 'john'
        john@yahoo.com  → 'john_a1b2'  (if 'john' is already taken)

    Args:
        email: A validated, lowercased email address. Must contain an '@'
            symbol — callers are responsible for validating the email before
            passing it to this function.

    Returns:
        A unique username string derived from the email local part.
    """
    local = email.split('@')[0][:141]

    if not CustomUser.objects.filter(username=local).exists():
        return local

    for _ in range(10):
        candidate = f'{local}_{secrets.token_hex(2)}'
        if not CustomUser.objects.filter(username=candidate).exists():
            return candidate

    return f'{local}_{secrets.token_hex(4)}'


def _serialize_user(user: CustomUser) -> dict:
    """Serializes a CustomUser instance into a dict matching UserSchema.

    Assumes households have already been prefetched on the queryset to
    avoid N+1 queries. At registration, the households list will be empty.

    Args:
        user: The CustomUser instance to serialize.

    Returns:
        A dict with user fields and a list of associated households.
    """
    return {
        'id': user.id,
        'username': user.username,
        'email': user.email,
        'first_name': user.first_name,
        'last_name': user.last_name,
        'households': [{'id': h.id, 'name': h.name} for h in user.households.all()],
    }
